### ISSUE TITLE
out = mamba_inner_fn(TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by SadInSummer** [Lizhe1228/MambaDFuse#10]
想问一下，就是我安装完环境之后，我import mamba_ssm之后不报错就说明我已经安装成功了吧，然后我把作者提供的mamba_simple放到了安装目录之下进行替换，然后进行test，报错了，
报错为：
File "/root/miniconda3/lib/python3.8/site-packages/mamba_ssm/modules/mamba_simple.py", line 383, in forward
out = mamba_inner_fn(TypeError: 'NoneType' object is not callable
数据，预训练模型什么的我都没有修改，只把测试代码中的gpu 0 1 2 修改为了0（因为我只有一块gpu）

**Comment by SadInSummer** [comment]
替换了文件，解决了

**Comment by xqoby** [comment]
你好，我也替换了mamba_simple.py(这个目录下的/data/xiaoxin/.conda/envs/MambaDFuse/lib/python3.8/site-packages/mamba_ssm/modules/mamba_simple.py) 文件，但是还是报out = mamba_inner_fn(TypeError: 'NoneType' object is not callable这个错，请问你怎么解决的呢？

**Comment by BigggZ123** [comment]
您好，请问直接整个包替换就行了嘛？那里面的__pycache__文件呢？

**Comment by siyao98** [comment]
> 你好，我也替换了mamba_simple.py(这个目录下的/data/xiaoxin/.conda/envs/MambaDFuse/lib/python3.8/site-packages/mamba_ssm/modules/mamba_simple.py) 文件，但是还是报out = mamba_inner_fn(TypeError: 'NoneType' object is not callable这个错，请问你怎么解决的呢？

你好，这个问题你解决了嘛？
