### ISSUE TITLE
怎么替换mamba_simple.py

### ISSUE THREAD

**Issue by tianxiaoer** [Lizhe1228/MambaDFuse#11]
After installing the Mamba library, replace the mamba_simple.py file in the installation directory with the ./mamba_simple.py in this repository.这句话是什么意思，不好意思没搞懂要怎么替换

**Comment by SadInSummer** [comment]
就是把这个文件放到你的mamba的安装路径同名的文件的位置就行

**Comment by Lizhe1228** [comment]
在你的虚拟环境库文件中，找mamba_ssm下的mamba_simple.py 用仓库中的该文件进行覆盖，如我的路径是.conda/envs/MambaDFuse/lib/python3.8/site-packages/mamba_ssm/modules/mamba_simple.py

**Comment by tianxiaoer** [comment]
好的好的感谢
