### ISSUE TITLE
causal_conv1d and mamba_ssm download link

### ISSUE THREAD

**Issue by MISlq** [Lizhe1228/MambaDFuse#2]
May I ask if it is possible to share the causal_conv1d=1.0.0 and mamba_ssm=1.0.1 files again on Baidu Netdisk?

Thanks

**Comment by MISlq** [comment]
Is there a download link for Windows causal_conv1d=1.0.0 and mamba_ssm?

**Comment by Lizhe1228** [comment]
https://pan.baidu.com/s/1BC_FJHMaHf_2KzcfkWE9vw?pwd=scis 
This linkis for Linux, and i have none for Windows.
