### ISSUE TITLE
指标问题

### ISSUE THREAD

**Issue by SunHui1216** [Lizhe1228/MambaDFuse#5]
感谢您这篇精彩的工作！
对于论文中测得的指标，我有以下问题：为啥本篇文章在MSRS数据集上，测得的CDDFuse的指标与CDDFuse原论文相差极大
![image](https://github.com/Lizhe1228/MambaDFuse/assets/55069547/5e0a6c1b-f0c2-4ea1-8331-8a0dde97bf0a)
![image](https://github.com/Lizhe1228/MambaDFuse/assets/55069547/ea967ef2-6534-452b-9858-e090e4e6ca89)
是因为测指标的方式不同吗？期待您的解答！

**Comment by Lizhe1228** [comment]
在本工作中，我们评测指标使用的方式参考的是https://github.com/Linfeng-Tang/Evaluation-for-Image-Fusion

**Comment by SunHui1216** [comment]
感谢您的解答！
