### ISSUE TITLE
百度网盘链接失效

### ISSUE THREAD

**Issue by Heiheicxx** [Lizhe1228/MambaDFuse#8]

**Comment by Lizhe1228** [comment]
https://pan.baidu.com/s/1BC_FJHMaHf_2KzcfkWE9vw?pwd=scis

**Comment by Lizhe1228** [comment]
https://pan.baidu.com/s/1BC_FJHMaHf_2KzcfkWE9vw?pwd=scis 这个应该好使

**Comment by Heiheicxx** [comment]
来信已收到^-^谢谢你的来信，保持联系

**Comment by Lizhe1228** [comment]
收到 祝科研顺利！
