### ISSUE TITLE
py文件缺失

### ISSUE THREAD

**Issue by SmartDarren** [Lizhe1228/MambaDFuse#9]
在 'imported module models' 中找不到引用 'model_plain2' 'model_plain4' 'model_gan'等模块，请问是特意撤换掉的吗？

**Comment by Lizhe1228** [comment]
您好，在本工作模型的训练当中并没有涉及到这些模块，代码中之所以有是因为，代码是基于其他仓库添加修改的，所以有些没用到的内容还并没有完全删除，对于给您带来的阅读代码观感性差的问题表达一下歉意。
